### ISSUE TITLE
Ecosis cannot download data

### ISSUE THREAD

**Issue by neo0351** [TESTgroup-BNL/How_to_PLSR#18]
Cannot download data using read.csv or read_csv.  Output for both provided.  However if i paste the URL into Chrome, it downloads the file.

```
dat_raw <- read.csv(ecosis_file, na.strings = "")
Error in file(file, "rt") : 
  cannot open the connection to 'https://ecosis.org/api/package/5617da17-c925-49fb-b395-45a51291bd2d/export?metadata=true'
In addition: Warning message:
In file(file, "rt") :
  URL 'https://ecosis.org/api/package/5617da17-c925-49fb-b395-45a51291bd2d/export?metadata=true': status was 'SSL peer certificate or SSH remote key was not OK'
```

```
dat_raw <- readr::read_csv(ecosis_file)
Error in open.connection(con, "rb") : 
  SSL certificate problem: certificate has expired
```

**Comment by neo0351** [comment]
@serbinsh This is a SSL certificate problem on EcoSIS's side.  Not sure how we can deal with it on ours, but I'll look into it once I finish my edits to the script.  Right now I'm just running with a downloaded copy to finish my testing.

**Comment by serbinsh** [comment]
@neo0351 I created an EcoSIS issue feel free to add comments there if you think there is more info that would help

**Comment by jrmerz** [comment]
Please try again.  SSL certs should be good to go.  Sorry about that.

**Comment by neo0351** [comment]
It's working now.
